name: Haskell CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ghc: ["8.6", "8.8", "8.10"]
        cabal: ["3.2"]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    # - uses: actions/cache@v2
    #   name: Cache ~/.cabal/packages
    #   with:
    #     path: ~/.cabal/packages
    #     key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages

    # - uses: actions/cache@v2
    #   name: Cache ~/.cabal/store
    #   with:
    #     path: ~/.cabal/store
    #     key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store

    - name: Build & test
      run: |
        ls -la
        cabal build all
        cabal test all
        cabal haddock
