name: Haskell CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ghc: ["8.6", "8.8", "8.10"]
        cabal: ["3.2"]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize'

    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@preview
      name: Cache ~/.cabal/packages
      with:
        path: ~/.cabal/packages
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages

    - uses: actions/cache@preview
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store

    - name: Install dependencies
      run: |
        cabal update
        cabal configure --write-ghc-environment-files=always -j2
        cabal build --only-dependencies

    - name: Build & test
      run: |
        cabal build
        cabal build example
        cabal test all
        cabal haddock
